apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service-app-metadata-name
  namespace: default
  labels:
    app: flight-service-app-metadata-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-service-app
  template:
    metadata:
      labels:
        app: flight-service-app
    spec:
      containers:
      - name: flight-service-app-container
        image: seemapawar/flight-service:4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9001

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flight-service-rollout
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-service-app
  strategy:
    blueGreen:
      activeService: flight-service-service
      previewService: flight-preview-service
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: flight-service-app
    spec:
      containers:
      - name: flight-service-app-container
        image: seemapawar/flight-service:4.0
        ports:
        - containerPort: 9001
