apiVersion: v1
kind: Service
metadata:
  name: flight-service-service
  namespace: default
spec:
  selector:
    app: flight-service-app
  ports:
  - port: 80
    targetPort: 9001

apiVersion: v1
kind: Service
metadata:
  name: flight-preview-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001
  selector:
    app: flight-service-app
